<a href="https://colab.research.google.com/github/nabil0day/Deep-Learning-for-Computer-Vision-with-Python-and-TensorFlow/blob/main/Practice_Day_01/Tensor_Flow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [19]:
tensor_one_d = tf.constant([2,0,-3,45,677], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([  2.   0.  -3.  45. 677.], shape=(5,), dtype=float32)


In [9]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [8,9,200],
    [22,31,222]
])
print(tensor_two_d)

tf.Tensor(
[[  1   2   3]
 [  4   5   6]
 [  8   9 200]
 [ 22  31 222]], shape=(4, 3), dtype=int32)


In [11]:
tensor_three_d = tf.constant([
    [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2 30]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 8  8  8]]

 [[ 1  1  1]
  [ 3  3  3]]

 [[ 6  6  6]
  [ 9  9  9]]], shape=(4, 2, 3), dtype=int32)


In [14]:
print(tensor_two_d.shape)

(4, 3)


In [17]:
print(tensor_three_d.ndim)

3


In [18]:
tensor_four_d = tf.constant([
   [ [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
   ],
      [ [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
   ],
      [ [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
   ],
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2 30]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 8  8  8]]

  [[ 1  1  1]
   [ 3  3  3]]

  [[ 6  6  6]
   [ 9  9  9]]]


 [[[ 1  2 30]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 8  8  8]]

  [[ 1  1  1]
   [ 3  3  3]]

  [[ 6  6  6]
   [ 9  9  9]]]


 [[[ 1  2 30]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 8  8  8]]

  [[ 1  1  1]
   [ 3  3  3]]

  [[ 6  6  6]
   [ 9  9  9]]]], shape=(3, 4, 2, 3), dtype=int32)


In [21]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [22]:
tensor_string = tf.constant("Hello This is Hadiur Rahman Nabil, Deep Learning for Computer Vision using Python and TensorFlow")
print(tensor_string)

tf.Tensor(b'Hello This is Hadiur Rahman Nabil, Deep Learning for Computer Vision using Python and TensorFlow', shape=(), dtype=string)


In [23]:
tensor_string = tf.constant(["Hello This is Hadiur Rahman Nabil", "Deep Learning for Computer Vision using Python and TensorFlow"])
print(tensor_string)

tf.Tensor(
[b'Hello This is Hadiur Rahman Nabil'
 b'Deep Learning for Computer Vision using Python and TensorFlow'], shape=(2,), dtype=string)


In [24]:
import numpy as np
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]
