<a href="https://colab.research.google.com/github/nabil0day/Deep-Learning-for-Computer-Vision-with-Python-and-TensorFlow/blob/main/Practice_Day_01/Tensor_Flow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [19]:
tensor_one_d = tf.constant([2,0,-3,45,677], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([  2.   0.  -3.  45. 677.], shape=(5,), dtype=float32)


In [9]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [8,9,200],
    [22,31,222]
])
print(tensor_two_d)

tf.Tensor(
[[  1   2   3]
 [  4   5   6]
 [  8   9 200]
 [ 22  31 222]], shape=(4, 3), dtype=int32)


In [11]:
tensor_three_d = tf.constant([
    [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2 30]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 8  8  8]]

 [[ 1  1  1]
  [ 3  3  3]]

 [[ 6  6  6]
  [ 9  9  9]]], shape=(4, 2, 3), dtype=int32)


In [14]:
print(tensor_two_d.shape)

(4, 3)


In [17]:
print(tensor_three_d.ndim)

3


In [18]:
tensor_four_d = tf.constant([
   [ [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
   ],
      [ [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
   ],
      [ [[1,2,30],
     [3,4,5]],
    [[4,5,6],
     [8,8,8]],
    [[1,1,1],
     [3,3,3]],
    [[6,6,6],
     [9,9,9]]
   ],
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2 30]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 8  8  8]]

  [[ 1  1  1]
   [ 3  3  3]]

  [[ 6  6  6]
   [ 9  9  9]]]


 [[[ 1  2 30]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 8  8  8]]

  [[ 1  1  1]
   [ 3  3  3]]

  [[ 6  6  6]
   [ 9  9  9]]]


 [[[ 1  2 30]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 8  8  8]]

  [[ 1  1  1]
   [ 3  3  3]]

  [[ 6  6  6]
   [ 9  9  9]]]], shape=(3, 4, 2, 3), dtype=int32)


In [21]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [22]:
tensor_string = tf.constant("Hello This is Hadiur Rahman Nabil, Deep Learning for Computer Vision using Python and TensorFlow")
print(tensor_string)

tf.Tensor(b'Hello This is Hadiur Rahman Nabil, Deep Learning for Computer Vision using Python and TensorFlow', shape=(), dtype=string)


In [23]:
tensor_string = tf.constant(["Hello This is Hadiur Rahman Nabil", "Deep Learning for Computer Vision using Python and TensorFlow"])
print(tensor_string)

tf.Tensor(
[b'Hello This is Hadiur Rahman Nabil'
 b'Deep Learning for Computer Vision using Python and TensorFlow'], shape=(2,), dtype=string)


In [24]:
import numpy as np
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [28]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [30]:
eye_tensor = tf.eye(
    num_rows= 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [31]:
eye_tensor = tf.eye(
    num_rows= 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(5*eye_tensor)

tf.Tensor(
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]], shape=(3, 3), dtype=float32)


In [32]:
eye_tensor = tf.eye(
    num_rows= 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [34]:
eye_tensor = tf.eye(
    num_rows= 5,
    num_columns=3,
    batch_shape=[2,5],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 5, 5, 3), dtype=float32)


In [35]:
fill_tensor = tf.fill(
    [3,4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [38]:
ones_tensor = tf.ones(
    [5,6],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(5, 6), dtype=float32)


In [40]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)
