<a href="https://colab.research.google.com/github/nabil0day/Deep-Learning-for-Computer-Vision-with-Python-and-TensorFlow/blob/main/Practice_Day_02/Tensor_Flow_Practice_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
zero_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zero_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [8]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [10]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)


<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [12]:
random_tensor = tf.random.normal(
    [5,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 2.7601748   1.2193135  -2.0908597 ]
 [-1.6059277  -0.582384    1.3035922 ]
 [ 0.18052389  1.6998352  -1.8021916 ]
 [-0.08840788  0.48662052  0.4496461 ]
 [-1.2747091   2.733951    0.35918948]], shape=(5, 3), dtype=float32)


In [13]:
random_tensor = tf.random.normal(
    [5,3],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.267944  99.20703   98.14954 ]
 [ 98.34594  101.055046  98.96124 ]
 [ 99.01215   99.92256   98.18528 ]
 [ 99.88765   98.93795   99.71479 ]
 [ 98.76951   98.6216    99.68665 ]], shape=(5, 3), dtype=float32)


In [4]:
rand_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(rand_tensor)

tf.Tensor([7.195943  3.2532787 3.819007  4.769129  6.410989 ], shape=(5,), dtype=float32)
