<a href="https://colab.research.google.com/github/nabil0day/Deep-Learning-for-Computer-Vision-with-Python-and-TensorFlow/blob/main/Practice_Day_03/Practice_Day_03_Tensors_and_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
import numpy as np

In [5]:
#Index
tensor_indexed = tf.constant([3,5,6,7,8,9,10,20])
print(tensor_indexed)
print(tensor_indexed[0:3])
print(tensor_indexed[1:3])
print(tensor_indexed[-1:1])
print(tensor_indexed[:-1])
#print(tensor_indexed)


tf.Tensor([ 3  5  6  7  8  9 10 20], shape=(8,), dtype=int32)
tf.Tensor([3 5 6], shape=(3,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 3  5  6  7  8  9 10], shape=(7,), dtype=int32)


In [3]:
tf.range(2,5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [7]:
tensor_math_abs = tf.math.abs(
    -5, name=None
)
print(tensor_math_abs)

tf.Tensor(5, shape=(), dtype=int32)


In [21]:
#abs
x_abs = tf.constant([-4,-5])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [26]:
x = tf.constant([-2+4j])
tf.abs(x)
#print(x)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([4.47213595])>

In [31]:
tf.sqrt(-2.2**2 + 4.0**2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.3406587>

In [34]:
#sqrt
input_value = tf.cast(-2**2 + 4**2, dtype=tf.float32)
result = tf.sqrt(input_value)
print(input_value)


tf.Tensor(12.0, shape=(), dtype=float32)


In [37]:
#addition
x_1 = tf.constant([1,2,3,4,5], dtype = tf.int32)
x_2 = tf.constant([6,7,8,9,10], dtype = tf.int32)
print(tf.add(x_1, x_2))

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)


In [38]:
#multiply
x_1 = tf.constant([1,2,3,4,5], dtype = tf.int32)
x_2 = tf.constant([6,7,8,9,10], dtype = tf.int32)
print(tf.multiply(x_1, x_2))

tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)


In [39]:
#subtract
x_1 = tf.constant([1,2,3,4,5], dtype = tf.int32)
x_2 = tf.constant([6,7,8,9,10], dtype = tf.int32)
print(tf.subtract(x_1, x_2))

tf.Tensor([-5 -5 -5 -5 -5], shape=(5,), dtype=int32)


In [40]:
#divide
x_1 = tf.constant([1,2,3,4,5], dtype = tf.int32)
x_2 = tf.constant([6,7,8,9,10], dtype = tf.int32)
print(tf.divide(x_1, x_2))

tf.Tensor([0.16666667 0.28571429 0.375      0.44444444 0.5       ], shape=(5,), dtype=float64)


In [44]:
#divide
x_1 = tf.constant([1,2,3,4,5], dtype = tf.float32)
x_2 = tf.constant([6,7,8,0,10], dtype = tf.float32)
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([0.16666667 0.2857143  0.375      0.         0.5       ], shape=(5,), dtype=float32)
