<a href="https://colab.research.google.com/github/nabil0day/Deep-Learning-for-Computer-Vision-with-Python-and-TensorFlow/blob/main/Day_03/Practice_Day_03_Tensors_and_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tensor_indexed = tf.constant([3,5,6,7,8,9,10,20])
print(tensor_indexed)
print(tensor_indexed[0:3])
print(tensor_indexed[1:3])
print(tensor_indexed[-1:1])
print(tensor_indexed[:-1])


tf.Tensor([ 3  5  6  7  8  9 10 20], shape=(8,), dtype=int32)
tf.Tensor([3 5 6], shape=(3,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 3  5  6  7  8  9 10], shape=(7,), dtype=int32)
