<a href="https://colab.research.google.com/github/nabil0day/Deep-Learning-for-Computer-Vision-with-Python-and-TensorFlow/blob/main/Practice_Day_04/Practice_Day_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(x_argmax.shape) #Just print the share # rows, 5 columns

(3, 5)


In [4]:
#argmax (Return that index that have maximum value)
x_argmax = tf.constant([2, 20, 30, 366, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [6]:
#argmin (Returt that index that have minimum value)
x_argmax = tf.constant([200, 20, 30, 366, 6])
print(tf.math.argmin(x_argmax))

tf.Tensor(4, shape=(), dtype=int64)


In [7]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(tf.math.argmax(x_argmax)) #For multidimentional axis
                                # Actually its find out the index in column wise

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [8]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(tf.math.argmin(x_argmax)) #For multidimentional axis
                                # Actually its find out the index in column wise

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)


In [2]:
# using power in multidimentional
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [4]:
#Reduce Sum
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [8,9,200],
    [22,31,222]
])
print(tensor_two_d)

print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(
[[  1   2   3]
 [  4   5   6]
 [  8   9 200]
 [ 22  31 222]], shape=(4, 3), dtype=int32)
tf.Tensor(513, shape=(), dtype=int32)


In [6]:
#Reduce Max
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [8,9,200],
    [22,31,222]
])
print(tensor_two_d)

print(tf.math.reduce_max(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(
[[  1   2   3]
 [  4   5   6]
 [  8   9 200]
 [ 22  31 222]], shape=(4, 3), dtype=int32)
tf.Tensor(222, shape=(), dtype=int32)


In [7]:
#Reduce Min
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [8,9,200],
    [22,31,222]
])
print(tensor_two_d)

print(tf.math.reduce_min(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(
[[  1   2   3]
 [  4   5   6]
 [  8   9 200]
 [ 22  31 222]], shape=(4, 3), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [10]:
#Changing Axis and Data Type of the previous Reduce Min Code
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [8,9,200],
    [22,31,222]], dtype = tf.float32
)
print(tensor_two_d)

print(tf.math.reduce_min(tensor_two_d, axis=0, keepdims=False, name=None))

tf.Tensor(
[[  1.   2.   3.]
 [  4.   5.   6.]
 [  8.   9. 200.]
 [ 22.  31. 222.]], shape=(4, 3), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
